<?php

namespace CourseFinderBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RevievRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevievRepository extends EntityRepository
{
}
